### PR TITLE
Client should now respect the maxBatchSize setting from the server

### PR DESCRIPTION
**Pull request by asafflesch**
Also added to log output how many requests used Bytestream vs CAS

### CODE REVIEW

**Comment by benjyw** [comment]
Will add @tdyas as a reviewer once he accepts the invite (he may be interested in toolchain's IP more generally)

**Comment by benjyw** [comment]
Thanks @Faqa - review pending. Please ping here if we don't get back to you in a few days.

**Comment by Faqa** [comment]
@benjyw  - Pinging as requested

(The build failure doesn't seem to be anything under my control?)

**Review by benjyw — APPROVED** [review]
Looks good to me, but I'll defer to @tdyas for a quick look.

**Review by tdyas — APPROVED** [review]
Seems fine to me.

**Comment by benjyw** [comment]
@Faqa - can you merge latest main into this branch? I fixed some CI bitrot there, so that should get this PR to pass CI. Thanks!

**Comment by benjyw** [comment]
@Faqa actually - wait until I fix the publishing CI job too... I'll ping here when it's good.

**Comment by benjyw** [comment]
@Faqa - OK, CI is fixed, so if you merge latest main onto your branch your CI should pass, and we can merge. Thanks for your patience!

**Comment by benjyw** [comment]
Merged, thanks again @Faqa

**Pull request merged**
