### PR TITLE
Add Dockerfile w/ casload & smoketest tools

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by tdyas** [comment]
1. It would be easier for users to consume both tools if each was the default entrypoint in its own image. 

2. The images should use the Docker [multi-stage build support](https://docs.docker.com/develop/develop-images/multistage-build/) so that the source code is not embedded in the final image. Basically just make the current build be the first-stage build and then add a second stage based on the applicable alpine image and copy the binary into place.

**Comment by asherf** [comment]
updated.
I will follow up w/ logic to add a GH workflow to push those to a register (either dockerhub or quay.io)
I suggest adding some versioning information to that binaries  (that can be printed using --version or something)
I think that would be useful.

**Comment by tdyas** [comment]
> I suggest adding some versioning information to that binaries (that can be printed using --version or something)

Good idea! Will do.

**Review by tdyas — APPROVED** [review]
lgtm

**Pull request merged**
